spring.application.name=kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.enable-auto-commit=true

spring.datasource.url=jdbc:mysql://mysql:3306/kafkademo
spring.datasource.username=root
spring.datasource.password=Adii@9389
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
